name = "PoroTomo"
uuid = "69f3b469-6f36-4c96-b466-60c2cf2f0e28"
authors = ["Tim Clements <thclements@g.harvard.edu> and contributors"]
version = "0.1.0"

[deps]
AWS = "fbe9abb3-538b-5e4e-ba9e-bc94f4f92ebc"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
SeisIO = "b372bb87-02dd-52bb-bcf6-c30dd83fd342"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
